title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Should be primary call-to-action, try not to overuse.

patterns:
  basic:
    title: "Basic"
    description: |
      Default button to use, most effective in front of dark backgrounds.
    width: "12em"
  ghost:
    title: "Ghost"
    description: |
    Ghost button is to be used in a situation where the objective isn't necessary to have the user interact with it.
    background: "--color-white"
